version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      MODEL_NAME: "default_model"
  
  frontend:
    image: streamlit
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    command: streamlit run /app/streamlit_ui.py